### ISSUE TITLE
Question about some of your aml files

### ISSUE THREAD

**Issue by snoby** [aluveitie/RyzenMacPro#1]
Hi,
I'm running a Ryzen hackintosh as well and came across your repository.  I followed the open core vanilla guide to get my system up and I noticed your repository is using several kext and other patches not in the vanilla guide.  I was interested in why?

for example: 
SSDT-HPET.aml
SSDT-PLUG.aml
SSDT-SBRG.aml
SSDT-XOSI.aml 

maybe there is a guide that I don't know about.

thanks

**Comment by aluveitie** [comment]
SSDT-PLUG.aml I got generated from this guide: https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/AMD/NullCPU-patch.md

I used SSDTTime to generate the SSDT-HPET.aml but this alone did not get HPET (High-Precision Event Timer) loading in MacOS. I've found the SSDT-SBRG.aml from some other X570 boards to get it loaded. The SSDT-XOSI.aml I think too (don't quite remember all the details) but may just be a left over from tinkering around... I'll check if it can't just be removed again.

So in Essence the SSDT-HPET/SSDT-SBRG/SSDT-XOSI are optional if you don't need HPET loaded.

**Comment by snoby** [comment]
Thanks for the help, I've noticed on my system that when doing a "transcode" with handbrake using videotoolbox that the system becomes very laggy.  I've checked with vidoproc and video encode and decode is hardware accelerated.  

I've implemented SSDT-PLUG with no change, I will net try SSDT-HPET.

If your interested here is my repository with the [EFI folder](https://github.com/snoby/hackintosh-x470-pro)

**Comment by aluveitie** [comment]
I've removed the SSDT-XOSI (which just makes the _OSI available for Windows) and the _OSI to XOSI rename as they are not needed.

My system handles transcoding with handbrake very well (either Software/CPU or Toolbox). I've never experienced any lagging even while working at the same time with more or less CPU intensive tasks.

To get HPET running I've had to use SSDT-HPET and SSDT-SBRG.

Thanks for sharing your EFI, always interested in learning what others do :)

**Comment by aluveitie** [comment]
@snoby You could also start Handbrake with nice to reduce its priority: 
```
nice -n 20 /Applications/HandBrake.app/Contents/MacOS/HandBrake &!
```
(I've used to do this on my old Quad-Core iMac because otherwise I could not really work with it while transcoding)

**Comment by snoby** [comment]
I'm thinking something still isn't right with this motherboard... may also be using it as an excuse to get the same MB as you have so that I can have thunderbolt again.

**Comment by aluveitie** [comment]
Just be aware that HotPlug is not working and I don't now yet of any fix.

ASRock did a really good job with this motherboard, but honestly the X570 is a bit overkill for ITX boards. Something like the B450A or upcoming B550 would be a much better fit (better thermals and on ITX boards only the CPUs PCIe 4.0 lanes are used anyway).
