### ISSUE TITLE
No installer disk listed

### ISSUE THREAD

**Issue by thbeh** [aluveitie/RyzenMacPro#10]
Hi, I recently got asrock-x570-itx MB using AMD 5500xt GPU card. I cloned your EFI  asrock-x570-itx branch but when I boot up, it didn't show the installer derive. It only showed Reset NVRAM. 

Did I missed anything. Please advice.

Thanks in advance.

**Comment by aluveitie** [comment]
This repo is not intended as a ready to install EFI but as a reference when following the Dortania guide.
The scan policy is set for the final system, you'd have to set it to 0 to see the installer.
