### ISSUE TITLE
config.plist file Corrupted 

### ISSUE THREAD

**Issue by johnlietzke** [aluveitie/RyzenMacPro#12]
Thanks for the detailed EFI.  

I am currently on OpenCore 0.6.8 with a 5950x and 6800 XT.  I was thinking of upgrading to 0.6.9 and noticed you were using VoodooTSCSyncAMD.   So I downloaded your EFI to take a look at the config.

Unfortunately, the config.plist is corrupted at line 195.

**Comment by aluveitie** [comment]
Thanks for noting, I’ll check and fix it next week when I merge the update to OpenCore 0.7.0

**Comment by johnlietzke** [comment]
I did not realize OpenCore 0.7.0 was out. 

Thanks, I will update this weekend also and compare it to your updated EFI.

**Comment by aluveitie** [comment]
OC releases usually come the first Monday each month, that would be next week

**Comment by johnlietzke** [comment]
It is already out but no release notes.  

https://github.com/dortania/build-repo/releases

This my first Hackintosh so I starting to get familiar with update cycles for the EFI.  It will be interesting if OpenCore 0.7.0 support the MacOS 12 beta that is coming on Monday.

**Comment by aluveitie** [comment]
Those are just snapshot builds of the latest commit, the final release is published on the acidanthera projects.

It is rather unlikely that Apple will again break everything already, but chances are some AMD kernel patch will break and we have to wait for the sources to be released until they can fix it.

**Comment by aluveitie** [comment]
fixed the schema error with todays update to 0.7.0

**Comment by johnlietzke** [comment]
I just wanted to let you know that MacOS 12 Monterey is going need an OpenCore update as you predicted.  If I have a 5950x would your VoodooTSCSyncAMD work as both our builds are 16 core?

What is the benefit of VoodooTSCSync vs SMCProcessor?

**Comment by aluveitie** [comment]
MacOS 12 works fine with current OC it seems. But the AMD Kernel patches need an update.

I've added VoodooTSCSyncAMD a long time ago... meanwhile I think it is not necessary, just haven't gotten around to remove it. The kext was designed to sync state on high core count CPUs, but everything is working just fine without it.

**Comment by johnlietzke** [comment]
A couple of questions:

Any problems with the 4002 bios?

Do you plan on updating 0.7.1 and dropping unraid?

Any problems with Monterey on AMD?

I have been traveling the last couple of weeks and will get home in a couple of days. Would you recommend holding off on updating a few days until 0.7.1 is released?
