### ISSUE TITLE
efi

### ISSUE THREAD

**Issue by yeapllg** [aluveitie/RyzenMacPro#13]
Hello, can you give me a full version of EFI file, which is applicable to Monterey. I still can't install it with your version 0.77. My motherboard, CPU and graphics card are the same as yours

**Comment by aluveitie** [comment]
What is the error message you’re stuck on?
Did you enter the correct core count in the first three kernel patches?

**Comment by yeapllg** [comment]
您好，您的邮件我已经收到，我会尽快联系您！！！

**Comment by aluveitie** [comment]
你好，没有问题，现在我不在家

**Comment by yeapllg** [comment]
你好，我用的黑果小兵的安装镜像，用你这边EFI后，发现不了安装monterey分区，但是能看见我的win分区和big sur分区我的scanplicy已经设置为0，

**Comment by yeapllg** [comment]
我把uefi里的openhfsplus.efi勾选上就能发现安装monterey分区了，但是点击安装后，跑完第一页代码就自动重启了，重启后再次进安装盘无任何输出

**Comment by yeapllg** [comment]
[config.plist.zip](https://github.com/aluveitie/RyzenMacPro/files/8058049/config.plist.zip)
这是我的config.plist

**Comment by nvollmar** [comment]
VoodooTSCSyncAMD.kext 不适用于 Monterey

你的 CPU 有多少个内核？

**Comment by aluveitie** [comment]
VoodooTSCSyncAMD.kext 不适用于 Monterey

你的 CPU 有多少个内核？

**Comment by yeapllg** [comment]
3950x 16核的

**Comment by yeapllg** [comment]
VoodooTSCSyncAMD.kext 这个文件我没动，是您EFI里面的，需要删掉么

**Comment by aluveitie** [comment]
是的，试试这个
[config.plist.zip](https://github.com/aluveitie/RyzenMacPro/files/8058153/config.plist.zip)

**Comment by aluveitie** [comment]
我还添加了核的数

**Comment by yeapllg** [comment]
刚刚用你这个config试了，还是不行，还是跑完第一页代码就重启了，3950x，6900xt，芝奇64G，博通的网卡，三星980pro固态，我的硬件就这些

**Comment by aluveitie** [comment]
添加 `keepsyms=1 debug=0x100` 到 boot-args
UEFI设置完成了吗？

**Comment by aluveitie** [comment]
使用 MacPro7,1 和 6900 XT，您不用 WhateverGreen

**Comment by yeapllg** [comment]
UEFI设置应该没问题，我现在机子上是big sur，用的0.6.4那个oc

**Comment by aluveitie** [comment]
我可以看看你的 0.6.4 config.plist 吗？

**Comment by yeapllg** [comment]
我把boot-args 改成了-v agdpmod=pikera keepsyms=1 debug=0x100，再试试看，
这是我big sur 的0.6.4oc config.plist
[config.plist.zip](https://github.com/aluveitie/RyzenMacPro/files/8058257/config.plist.zip)
，

**Comment by yeapllg** [comment]
刚刚试了一下，还是跟之前一样，不行，你的EFI能给我试试么，配置一样的话

**Comment by aluveitie** [comment]
当您将 iMacPro1,1 更改为 MacPro7,1 时，您需要新的 MLB/SystemSerialNumber

**Comment by yeapllg** [comment]
MLB/SystemSerialNumber，这两个值我改了的

**Comment by yeapllg** [comment]
我在本机上先用occ改成的MacPro7,1，然后把MLB/SystemSerialNumber再复制过去的

**Comment by aluveitie** [comment]
这是我当前的 EFI（没有序列号）:
[EFI.zip](https://github.com/aluveitie/RyzenMacPro/files/8058383/EFI.zip)

我不将板载 NIC 与 Monterey 一起使用

**Comment by yeapllg** [comment]
我把序列号加上试试看，谢谢

不将板载 NIC 与 Monterey 一起使用    这个需要设置哪里吗？

**Comment by aluveitie** [comment]
我正在使用 5GBe NIC (pacific.kext)。 对于 I211-AT，请使用：https://github.com/donatengit/AppleIGB/releases

**Comment by yeapllg** [comment]
安装上了，谢谢，wifi正常，有线即使我用AppleIGB.kext也不正常，显示能连接上，但是无法上网，不知道哪里的问题。

**Comment by aluveitie** [comment]
带有 I211-AT 的以太网是 Monterey 的问题

**Comment by yeapllg** [comment]
你好，请问6900xt显卡在12.3里面需要怎么设置，我这升级完后某些界面有些卡顿，比如终端和QQ界面，在拉升和放大缩小的时候会很卡顿，而浏览器和某些原生应用就不卡，应该就是显卡设置问题。

**Comment by aluveitie** [comment]
12.3 严重破坏了 Navi GPU 的 METAL 性能。 要修复它，您必须切换帧缓冲区：https://github.com/aluveitie/RyzenMacPro/blob/bd8c82f1d64060954aeaa319b0d35de448639ec9/EFI-BareMetal/OC/config.plist#L168

**Comment by aluveitie** [comment]
@yeapllg 昨天的 12.3.1 更新修复了 NAVI GPU 问题

**Comment by yeapllg** [comment]
你好，你能把你的0.79EFI文件发给我参考一下么，我下载后把之前的覆盖了无法启动，不知道哪里的问题。

**Comment by yeapllg** [comment]
你好，我按照你信的config，提示以下：
OC: Plist Kexts\AppleMCEReporterDisabler.kext\Contents\Info.plist is missing for injected kext AppleMCEReporterDisabler.kext (V I Required for 12.3)
Halting on critical error

升级后就这样了，用之前的efi也不行

**Comment by aluveitie** [comment]
您是否将 AppleMCEReporterDisabler.kext 添加到 EFI？

**Comment by yeapllg** [comment]
添加了，在这里下载的，https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip
把这个去掉后，跑完第一屏代码就直接重启了，也无法启动

**Comment by aluveitie** [comment]
你能上传你的EFI吗

**Comment by yeapllg** [comment]
[EFI.zip](https://github.com/aluveitie/RyzenMacPro/files/8414391/EFI.zip)
你好，您给看看，我这个就就是直接从您上面下载的EFI-BareMetal里的config.plist

**Comment by aluveitie** [comment]
我看到两个问题

您需要设置核心数: algrey - Force cpuid_cores_per_package 12.0
您需要在 BIOS 中禁用 Intel I211AT NIC 或设置 boot-args dk.e1000=0

**Comment by yeapllg** [comment]
设置核心数量，我在467行那个不对么，我看跟之前0.78是一样的，能把您的EFI发我一下么，我把序列号改成我的就行了。
`<dict>
                    <key>Arch</key>
                    <string>x86_64</string>
                    <key>Base</key>
                    <string>_cpuid_set_info</string>
                    <key>Comment</key>
                    <string>algrey - Force cpuid_cores_per_package 12.0</string>
                    <key>Count</key>
                    <integer>1</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>wegaAAAA</data>
                    <key>Identifier</key>
                    <string>kernel</string>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data>//3/AAAA</data>
                    <key>MaxKernel</key>
                    <string>21.99.99</string>
                    <key>MinKernel</key>
                    <string>21.0.0</string>
                    <key>Replace</key>
                    <data>ugAAAACQ</data>
                    <key>ReplaceMask</key>
                    <data>////////</data>
                    <key>Skip</key>
                    <integer>0</integer>
                </dict>`

**Comment by aluveitie** [comment]
未设置核心数:
![Screenshot 2022-04-05 at 07 26 47](https://user-images.githubusercontent.com/61966108/161684921-a3374b08-61a7-4c26-9d38-093c621d4a69.png)

**Comment by yeapllg** [comment]
你好，我把algrey - Force cpuid_cores_per_package 12.0改了，dk.e1000=0也添加了，现在 AppleMCEReporterDisabler.kext这个能加载，但是最后还是无法启动，加载完第一屏代码后就直接重启了
![QQ截图20220406110619](https://user-images.githubusercontent.com/52744942/161888350-d9908c5f-9f4f-4ba7-b0db-851af1107c09.png)
。

**Comment by aluveitie** [comment]
你是否启用了 Above4GDecoding，是否启用了 ResizableBAR？

**Comment by yeapllg** [comment]
您好，我根据您上面的bios设置，Above 4G 启动，RezisableBAR 关闭！

https://user-images.githubusercontent.com/52744942/161892066-e4d55281-cb64-41c4-bb4c-91d5ad8cdfaa.mp4
![QQ图片20220406114917](https://user-images.githubusercontent.com/52744942/161892120-b6f84b34-91b4-458c-b0c2-69ba5420d1a8.jpg)
![QQ图片20220406114927](https://user-images.githubusercontent.com/52744942/161892122-bfe7b615-376b-4d8d-8a5f-8272a72e7eee.jpg)

**Comment by aluveitie** [comment]
将 debug=0x100 keepsyms=1 添加到 boot-args 以查看它停止的位置
你也可以尝试在 BIOS 中禁用 NIC

**Comment by yeapllg** [comment]
添加debug=0x100 keepsyms=1这个后，还是和视频中一样，跑完第一屏就重启了

**Comment by aluveitie** [comment]
安装 12.3.1 时，你可以删除它：
<img width="577" alt="Screenshot 2022-04-06 at 06 24 00" src="https://user-images.githubusercontent.com/61966108/161895434-20533900-e50c-485b-a05f-d7098f6d79c9.png">

**Comment by yeapllg** [comment]
能启动了，把这个删掉就能启动了，太感谢了。

**Comment by aluveitie** [comment]
不客气，很高兴我能帮上忙
