### ISSUE TITLE
Big Sur - SMCAMD

### ISSUE THREAD

**Issue by kaiserdan** [aluveitie/RyzenMacPro#4]
Thanks so much for this amazing repo it helped me enormously.

Did you manage to find a solution for SMCAMDProcessor or the RyzenPowerTools on BigSur? I saw your post in the other repo @aluveitie, and would be curious if you were successful after all, or if you're waiting for an update/change from the devs.

**Comment by aluveitie** [comment]
Glad it helped :)

I did not get around to look deeper into it but I gathered a few things I could try until Lilu supports Big Sur userspace patching.

Otherwise 0.3.4 and older versions are reported to still work on Big Sur.
