### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by vanities** [aluveitie/RyzenMacPro#5]
Thanks for your repo, gleaning some things about hibernation in here. Just wanted to ask if you had gotten any type of microphone working, neither my front panel, nor bluetooth (with IntelBlueTooth kext) works :(.

Also:

> no intel wifi drivers

check out https://github.com/OpenIntelWireless/itlwm, they just v1d 6 days ago, working alright on my card, albeit N band.

**Comment by aluveitie** [comment]
AppleALC does not support mics on AMD in general, you could use VoodooHDA instead as far as I know.
IntelBluetooth kext only uploads the firmware which is compatible enough for Apple's bluetooth driver, but not everything works. Another option would be a USB audio interface.

I was following the itlwm project for some time, I should update the Readme in that regard. I've never bothered with Wifi as the only use I'd have for it would be AirDrop/Apple Watch unlock which does not work as it's implemented as a Ethernet device. I'm planning to replace my AX200 with a Broadcom one to get Mic Bluetooth and AirDrop working once I have time to re-build my rig.
