### ISSUE TITLE
SBUS controller / SSDT-SBUS-MCHC.aml

### ISSUE THREAD

**Issue by EarlOfBurton** [aluveitie/RyzenMacPro#7]
Hello aluveitie,

thanks for your work!

I see that there are two files in your ACPI folder named:
SSDT-SBUS-MCHC_2.30.aml
and
SSDT-SBUS-MCHC_2.00.aml

But in your config.plist I can find a call for SSDT-SBUS-MCHC.aml only
(at the time of writing lines 41-48).
			<dict>
				<key>Comment</key>
				<string>SBUS controller fix</string>
				<key>Enabled</key>
				<false/>
				<key>Path</key>
				<string>SSDT-SBUS-MCHC.aml</string>
			</dict>

Is it better to leave that out of the config because your path seems to go nowhere?
Can I also ask you, what is this file for?

Regards

**Comment by aluveitie** [comment]
The specific ACPI paths changed between BIOS 2.00 and 2.30+. You'd need to choose depending on the BIOS version you're using.

The SSDT gets MacOS to load the drivers for the SMBus controller. It should slightly reduce the systems power consumption but is not required at all. One drawback is, on X570 it seems to break sleep (not so on B550 as I've heard).

**Comment by EarlOfBurton** [comment]
Oh, I see, thank you very much. Since I'm on the same mainboard as you I'll leave it disabled then.
